openapi: 3.0.0
info:
  title: A Simple User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Returns a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
    post:
      summary: Create a new user
      responses:
        '201':
          description: A new user has been created
